simple-coder:
  repo-root: ${user.dir}
  max-file-lines: 500
  max-search-results: 50
  context-history-size: 10

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo

server:
  port: 8080
