simple-coder:
  # ${user.dir} is a Java system property that resolves to the current working directory
  # where the application is started. This ensures file operations are relative to the project root.
  repo-root: ${user.dir}
  max-file-lines: 500
  max-search-results: 50
  max-list-results: 200
  agent:
    max-steps: 10

spring:
  ai:
    openai:
      api-key: dummy-local
      base-url: http://localhost:4141
      chat:
        options:
          model: gpt-4.1

server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
    com.simplecoder.config.SimpleLoggerAdvisor: INFO
