simple-coder:
  # ${user.dir} is a Java system property that resolves to the current working directory
  # where the application is started. This ensures file operations are relative to the project root.
  repo-root: ${user.dir}
  max-file-lines: 500
  max-search-results: 50
  max-list-results: 200
  agent:
    max-steps: 10

spring:
  ai:
    openai:
      api-key: dummy-local
      base-url: http://localhost:4142
      chat:
        options:
          model: gpt-5-mini

server:
  port: 8080

logging:
  level:
    # HTTP layer - logs raw request/response for each LLM API call
    com.simplecoder.config.HttpLoggingConfig: INFO
    
    # Tool execution layer - logs tool invocations
    com.simplecoder.service.ToolsService: INFO
    org.springframework.ai.model.tool: DEBUG
    
    # High-level context layer - logs first/last turn
    com.simplecoder.config.SimpleLoggerAdvisor: INFO
